data:
  AzureWebJobsStorage: ''
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsFeatureFlags: RW5hYmxlV29ya2VySW5kZXhpbmc=
apiVersion: v1
kind: Secret
metadata:
  name: minhnt47cluster
---
data:
  host.master: Y0s1V0tvcTI1MjN6VEZqSUlHV1JmTE8yZHZvWWFmcFRZZTRHaFhRUHpXMllBekZ1dVUzWGVnPT0=
  host.function.default: X3BHckh6cE1vZTRhT05MQ3psY2gzclkzeWJkc1R1RnIxSk5YVzNFRG5ZMGFBekZ1c2FDejl3PT0=
  host.systemKey.default: TEEtMjZIS1lCQ3hma2NzQVBYU1dRYlJ4UkF1WFRmYmduX1o2VzFna293Z01BekZ1QjZmS1JnPT0=
  functions.createadvertisement.default: ekdNbGtjY0h6TE52VGZsMlhnQUxXc2xvYWF4LTJ5aHlDNmpDYzFzUlk0MWdBekZ1YmlkSU5BPT0=
  functions.deleteadvertisement.default: YTl6TTNoN2dHUHM0UXU4TmZzV3B3U0tHeVZNaHdPRFktX0s1b1N3VlU2Z29BekZ1dEhjZ2VRPT0=
  functions.getadvertisement.default: aWtPSlFBNzZISWJid0RnMkpPSzQ2VjBSOFMzaS1rSnBKNDB5LXBJMGF4VElBekZ1U0FMZEl3PT0=
  functions.getadvertisements.default: UnpLT2JZU2J0cWhoc0dPeGNQaGFiVzNwd3AzencxOWlBTUw1bzZ4NDFwRklBekZ1cTR2ZjZRPT0=
  functions.getpost.default: djBMbjRxNDJXcjM3Zi1IQm8zS0ljWDl3R0ZhSHlOaFdHVk9JcnY4Y19kNEZBekZ1ZGU5WlB3PT0=
  functions.getposts.default: R1laWExmQkpHZzU5dmRXNnVLeXFKOGVsWmtpckJLby1Lal9kdkZfbllqamFBekZ1T0RKUjlnPT0=
  functions.updateadvertisement.default: NUpMYTlqSDhOckF3S0k2LXhDZmJaM1RTRHVOdmdDeUJMdDBKRnBzelc3YWhBekZ1ZnIyUVlRPT0=
apiVersion: v1
kind: Secret
metadata:
  name: func-keys-kube-secret-minhnt47cluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: minhnt47cluster-function-keys-identity-svc-act
---
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: functions-keys-manager-role
---
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: functions-keys-manager-role
subjects:
- kind: ServiceAccount
  name: minhnt47cluster-function-keys-identity-svc-act
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minhnt47cluster-function-keys-identity-svc-act-functions-keys-manager-rolebinding
---
apiVersion: v1
kind: Service
metadata:
  name: minhnt47cluster-http
spec:
  selector:
    app: minhnt47cluster-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minhnt47cluster-http
  labels:
    app: minhnt47cluster-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minhnt47cluster-http
  template:
    metadata:
      labels:
        app: minhnt47cluster-http
    spec:
      containers:
      - name: minhnt47cluster-http
        image: minhnt47registry.azurecr.io/minhnt47registry:latest
        ports:
        - containerPort: 80
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: createAdvertisement
        - name: AzureFunctionsJobHost__functions__1
          value: deleteAdvertisement
        - name: AzureFunctionsJobHost__functions__2
          value: getAdvertisement
        - name: AzureFunctionsJobHost__functions__3
          value: getAdvertisements
        - name: AzureFunctionsJobHost__functions__4
          value: getPost
        - name: AzureFunctionsJobHost__functions__5
          value: getPosts
        - name: AzureFunctionsJobHost__functions__6
          value: updateAdvertisement
        - name: AzureWebJobsSecretStorageType
          value: kubernetes
        - name: AzureWebJobsKubernetesSecretName
          value: secrets/func-keys-kube-secret-minhnt47cluster
        envFrom:
        - secretRef:
            name: minhnt47cluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: minhnt47cluster-function-keys-identity-svc-act
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minhnt47cluster
  labels:
    app: minhnt47cluster
spec:
  selector:
    matchLabels:
      app: minhnt47cluster
  template:
    metadata:
      labels:
        app: minhnt47cluster
    spec:
      containers:
      - name: minhnt47cluster
        image: minhnt47registry.azurecr.io/minhnt47registry:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: eventHubTrigger
        envFrom:
        - secretRef:
            name: minhnt47cluster
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
      serviceAccountName: minhnt47cluster-function-keys-identity-svc-act
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: minhnt47cluster
  labels: {}
spec:
  scaleTargetRef:
    name: minhnt47cluster
  triggers:
  - type: eventgridtrigger
    metadata:
      direction: in
      eventHubName: testhub
      connection: Endpoint=sb://udacityneighborly.servicebus.windows.net/;SharedAccessKeyName=allpolicy;SharedAccessKey=LOxUOkN13xN038T1VoSsmaTt4s7vq/+VCzduS5/nH9A=;EntityPath=testhub
---

